version: "3.7"
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: tandm_programming_challenge
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    image: tandm-programming-challenge
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"